defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: circleci/node:12.1

### ORBS
orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.8

### EXECUTORS
executors:
  lighthouse-server:
    docker:
      - image: orbies/lighthouse-ci@0.1.0

### JOBS
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths: .

  bundle_dependencies:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-{{ .Environment.CACHE_VERSION }}
      - run: npm install
      - save_cache:
          paths:
          - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-{{ .Environment.CACHE_VERSION }}

      - run: npm run build

      - persist_to_workspace:
          root: ./
          paths:
          - .next


  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-{{ .Environment.CACHE_VERSION }}

      - run: npm run test
  perf:
    executor: lighthouse-check
    steps:
    - attach_workspace:
        at: ~/repo
    - restore_cache:
        keys:
        - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
        # fallback to using the latest cache if no exact match is found
        - dependencies-{{ .Environment.CACHE_VERSION }}
    - run: sudo npm install -g @lhci/cli@0.6.1
    - run:
        name: lhci autorun
        command: |
          echo
          lhci autorun

### WORKFLOWS 

version: 2.1
workflows:
  build-and-test:
    jobs:
    - checkout_code:
        filters:
          branches:
            ignore: /develop|master/
    - bundle_dependencies:
        requires:
        - checkout_code
        filters:
          branches:
            ignore: /develop|master/
    - test:
        requires:
        - bundle_dependencies
        filters:
          branches:
            ignore: /develop|master/
    - build:
        requires:
        - bundle_dependencies
        filters:
          branches:
            ignore: /develop|master/
    - perf:
        requires:
        - build
        filters:
          branches:
            ignore: /develop|master/
