
### ORBS
orbs:
  lighthouse-check: sebasrodriguez/lighthouse-check@0.1.0

### JOBS
jobs:
  test:
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          apiToken: $LIGHTHOUSE_CHECK_API_TOKEN
          urls: 'https://heycar.co.uk,https://heycar.co.uk/audi'

### WORKFLOWS         
version: 2.1
workflows:
  test:
    jobs:
      - test